services:

  pgadmin:
    image: dpage/pgadmin4:latest

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    networks:
      - rede_interna

    environment:
      - PGADMIN_DEFAULT_EMAIL=contato@ojauum.com.br
      - PGADMIN_DEFAULT_PASSWORD=serfgs1gse6g21se65g1s3

    ports:
      - "8082:80"  # Porta local:porta do container (pode ajustar a porta local se necessário)

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 1024M

volumes:
  pgadmin_data:
    external: true

networks:
  rede_interna:
    name: rede_interna
    external: true
